name: Update Team Members and Events

on: workflow_dispatch

jobs:
  update-team-members-and-events:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.23.0"

      - name: Run main.go
        env:
          STRAPI_URL: ${{ secrets.STRAPI_URL }}
          STRAPI_API_KEY: ${{ secrets.STRAPI_API_KEY }}
        run: go run ./cmd/main.go

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Auto Update Team Members and Events
